---
title: "02_Exploratory_Data_Analysis"
output: html_document
date: "2024-08-22"
---

```{r}
library(dplyr)
library(knitr)
library(kableExtra)
library(corrplot)
library(ggcorrplot) 
```


# Load the Data
```{r}
# Loading all data
alldata <- readRDS('./results/all_data.rds')

head(alldata, n = 10)

str(alldata)
```

# Descriptive Statistics
```{r}
# Exclude -999.00 data
alldata <- alldata[alldata$Element_Value_ppm != -999.00, ]

# Populate descriptive stats table
desc_stats <- alldata %>%
  group_by(Element_Symbol, Element_Description) %>%
  summarise(min = min(Element_Value_ppm),
         max = max(Element_Value_ppm),
         mean = mean(Element_Value_ppm),
         median = median(Element_Value_ppm),
         range = max(Element_Value_ppm) - min(Element_Value_ppm),
         q1 = quantile(Element_Value_ppm, 0.25),
         q3 = quantile(Element_Value_ppm, 0.75),
         iqr = IQR(Element_Value_ppm),
         sd = sd(Element_Value_ppm),
         var = var(Element_Value_ppm))

kable(desc_stats)
```

# Correlation Analysis
```{r}

```

# Distribution of elements with reference to PASS levels
```{r}
alldata %>%
  ggplot(aes(x = PAAS_normalised_value, y = Element_Symbol, color = Above_PASS_flag)) +
  geom_point() +
  geom_vline(xintercept = 1, linetype = 2) +
  theme_bw() +
  scale_color_brewer(palette = "Set1")
```

```{r}
alldata %>%
  group_by(Project_Name, Above_PASS_flag) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = Above_PASS_flag, y = count, fill = Above_PASS_flag)) +
  geom_col() +
  facet_wrap(~ Project_Name) +
  theme_bw() +
  theme(axis.text.x = element_blank()) +
  scale_fill_brewer(palette = "Set1")
```


# Distribution Analysis
```{r}
alldata %>%
  ggplot(aes(x = PAAS_normalised_value, y = Element_Symbol)) +
  geom_boxplot() +
  geom_vline(xintercept = 1, linetype = 2) +
  theme_classic()
```

```{r}
alldata %>%
  ggplot(aes(x = PAAS_normalised_value, y = Element_Symbol, color = Above_PASS_flag)) +
  geom_point() +
  geom_vline(xintercept = 1, linetype = 2) +
  scale_color_brewer(palette = "Set1") +
  facet_wrap(~ Project_Name) +
  theme_bw()
```


# Scatter Plot



# Cor plot

```{r}
res_cor_cop <- alldata %>% 
  select(Project_Name,Sample_ID,Element_Symbol,Element_Value_ppm) %>% 
  pivot_wider(names_from = Element_Symbol,values_from = c(Element_Value_ppm))

corr_cop <- cor(res_cor_cop[,3:56])


pg_cop <- ggcorrplot(corr_cop,type = "lower",
     outline.col = "white", lab = TRUE, lab_size = 2)

print(pg_cop)
```




